# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  unit_tests:
    docker:
      # specify the version you desire here
      - image: toplprotocol/graalvm-jdk11-21.1.0-test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      SBT_VERSION: 1.5.5
      TERM: dumb

    steps:

      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: sbt-cache
      - run: sbt + update

      - save_cache:
          paths:
            - ~/.m2
            - ~/.ivy2
            - ~/.sbt
          key: v1-dependencies--{{ checksum "build.sbt" }}

      # run tests!
      - run: sbt checkPR

workflows:
  version: 2
  tests:
    jobs:
      - unit_tests
