# Scala CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/sample-config/ for more details
#
version: 2
jobs:
  unit_tests:
    docker:
      # specify the version you desire here
      - image: oracle/graalvm-ce:19.2.0
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    working_directory: ~/repo

    environment:
      SBT_VERSION: 0.13.17
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3600m
      #SBT_OPTS: -XX:MaxMetaspaceSize=512M -Xmx6G # <- Graal is saying this is was deprecated
      TERM: dumb
    
    steps:

      - run:
          name: Get sbt binary
          command: |
            yum update -y
            curl https://bintray.com/sbt/rpm/rpm | tee /etc/yum.repos.d/bintray-sbt-rpm.repo
            yum install -y sbt git

      - checkout

      - run:
          name: Add Valkyrie instrument to boot classpath
          command: cp ~/bifrost/lib/ValkyrieInstrument-1.0.jar /opt/graalvm-ce-19.2.0/jre/lib/boot/

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "build.sbt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: cat /dev/null | sbt test:compile

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
        
      # run tests!
      - run: cat /dev/null | sbt -mem 2048 test:test

workflows:
  version: 2
  tests:
    jobs:
      - unit_tests
