apiVersion: 1

datasources:
  - id: 1
    orgId: 1
    name: "InfluxDB"
    type: "influxdb"
    typeLogoUrl: "public/app/plugins/datasource/influxdb/img/influxdb_logo.svg"
    database: "mydb"
    access: "direct"
    url: "http://localhost:8086"
    password: ""
    user: ""
    basicAuth: false
    isDefault: false
    jsonData: {}
    readOnly: false

  - id: 2
    orgId: 1
    name: Prometheus
    type: prometheus
    typeLogoUrl: public/app/plugins/datasource/prometheus/img/prometheus_logo.svg
    access: direct
    url: http://localhost:9090
    password: ''
    user: ''
    database: ''
    basicAuth: false
    isDefault: true
    jsonData: {}
    readOnly: false
