version: "3.7"

services:
  node1:
    image: toplprotocol/bifrost-node-tetra
    command: --config /mnt/special-config.conf --testnetTimestamp 1663709803682 --testnetStakerIndex 0
    volumes:
      - ./special-config.conf:/mnt/special-config.conf
  node2:
    image: toplprotocol/bifrost-node-tetra
    command: --config /mnt/special-config.conf --testnetTimestamp 1663709803682 --testnetStakerIndex 1
    volumes:
      - ./special-config.conf:/mnt/special-config.conf
    environment:
      - BIFROST_P2P_KNOWN_PEERS=node1:9085