name: Publish Docker Images (Dev)

on:
  workflow_call:

jobs:
  publish_docker_images:
    name: Publish Docker Images
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      # First publish strata-node to Dockerhub and GHCR (dev image).
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images to registries
        run: DOCKER_PUBLISH_DEV_TAG=true sbt node/Docker/publish indexer/Docker/publish
