name: Publish Docker Image (Release)

on:
  workflow_call:
    inputs:
      target-os:
        description: 'List of operating systems to build on.'
        default: "['ubuntu-latest']"
        required: false
        type: string
      java-versions:
        description: 'List of Java versions to target.'
        default: "['21']"
        required: false
        type: string

jobs:
  docker_release:
    strategy:
      matrix:
        os: ${{fromJson(inputs.target-os)}}
        java: ${{fromJson(inputs.java-versions)}}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Github Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push images to registries
        run: DOCKER_PUBLISH_LATEST_TAG=true sbt node/Docker/publish indexer/Docker/publish
