name: Scala Assemble JAR

on:
  workflow_call:
    inputs:
      target-os:
        description: 'List of operating systems to build on.'
        default: "['ubuntu-latest']"
        required: false
        type: string
      java-versions:
        description: 'List of Java versions to target.'
        default: "['21']"
        required: false
        type: string
      preserve-cache-between-runs:
        description: 'Preserve project cache between new runs.'
        default: false
        required: false
        type: boolean

jobs:
  build:
    name: Assemble JAR
    strategy:
      matrix:
        os: ${{fromJson(inputs.target-os)}}
        java: ${{fromJson(inputs.java-versions)}}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need full history to update last modified time.
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          cache: 'sbt'

      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.10.6

      - name: git-restore-mtime
        uses: chetan/git-restore-mtime-action@v1

      - name: Compile
        run: sbt node/assembly

      - name: Upload JAR
        uses: actions/upload-artifact@v3
        with:
          name: Plasma Node Jar (${{ matrix.java }})
          path: node/target/scala-3.*.*/plasma-node-*.jar
          if-no-files-found: error
      
