name: Bifrost_CI

on:
  push:
    branches: [dev, main, release-*, rc-*]
    tags: ['*']
  workflow_dispatch:

jobs:
  validate-helm:
    uses: ./.github/workflows/_validate_helm.yml

  sbt-build:
    uses: ./.github/workflows/_sbt_build.yml
    with:
      target-os: >-
        ["ubuntu-latest"]
      java-versions: >-
        ["11"]

  publish-docker-image-dev-node:
    if: ${{ github.ref_name == 'dev' }}
    uses: ./.github/workflows/_docker_publish.yml
    needs: sbt-build
    with:
      remote-repository: "us-central1-docker.pkg.dev/topl-shared-project-dev/topl-artifacts-dev"
      registry-auth-location: "us-central1-docker.pkg.dev"
      local-docker-repo: "toplprotocol"
      local-docker-image: "bifrost-node"
      scala-project: "node"
    secrets: inherit

  publish-docker-image-dev-testnet-orchestrator:
    if: ${{ github.ref_name == 'dev' }}
    uses: ./.github/workflows/_docker_publish.yml
    needs: sbt-build
    with:
      remote-repository: "us-central1-docker.pkg.dev/topl-shared-project-dev/topl-artifacts-dev"
      registry-auth-location: "us-central1-docker.pkg.dev"
      local-docker-repo: "toplprotocol"
      local-docker-image: "testnet-simulation-orchestrator"
      scala-project: "testnetSimulationOrchestrator"
    secrets: inherit

  publish-docker-image-dev-network-delayer:
    if: ${{ github.ref_name == 'dev' }}
    uses: ./.github/workflows/_docker_publish.yml
    needs: sbt-build
    with:
      remote-repository: "us-central1-docker.pkg.dev/topl-shared-project-dev/topl-artifacts-dev"
      registry-auth-location: "us-central1-docker.pkg.dev"
      local-docker-repo: "toplprotocol"
      local-docker-image: "network-delayer"
      scala-project: "networkDelayer"
    secrets: inherit

  publish-docker-image-qa-node:
    if: ${{ startsWith(github.ref_name, 'release-') }}
    uses: ./.github/workflows/_docker_publish.yml
    needs: sbt-build
    with:
      remote-repository: "us-central1-docker.pkg.dev/topl-shared-project-qa/topl-artifacts-qa"
      registry-auth-location: "us-central1-docker.pkg.dev"
      local-docker-repo: "toplprotocol"
      local-docker-image: "bifrost-node"
      scala-project: "node"
    secrets: inherit

  publish-docker-image-qa-testnet-orchestrator:
    if: ${{ startsWith(github.ref_name, 'release-') }}
    uses: ./.github/workflows/_docker_publish.yml
    needs: sbt-build
    with:
      remote-repository: "us-central1-docker.pkg.dev/topl-shared-project-qa/topl-artifacts-qa"
      registry-auth-location: "us-central1-docker.pkg.dev"
      local-docker-repo: "toplprotocol"
      local-docker-image: "testnet-simulation-orchestrator"
      scala-project: "testnetSimulationOrchestrator"
    secrets: inherit

  publish-docker-image-qa-network-delayer:
    if: ${{ startsWith(github.ref_name, 'release-') }}
    uses: ./.github/workflows/_docker_publish.yml
    needs: sbt-build
    with:
      remote-repository: "us-central1-docker.pkg.dev/topl-shared-project-qa/topl-artifacts-qa"
      registry-auth-location: "us-central1-docker.pkg.dev"
      local-docker-repo: "toplprotocol"
      local-docker-image: "network-delayer"
      scala-project: "networkDelayer"
    secrets: inherit

  publish-docker-image-main:
    # Execute if ref is a tag, and the format starts with v like v1.2.1.
    if: ${{ startsWith(github.ref_name, 'v') && github.ref_type == 'tag' }}
    uses: ./.github/workflows/_docker_publish_official.yml
    needs: sbt-build
    secrets: inherit

  sbt-integration-tests:
    uses: ./.github/workflows/_scala_integration_tests.yml
    needs: sbt-build
    with:
      target-os: >-
        ["ubuntu-latest"]
      java-versions: >-
        ["11"]

  publish-test-results:
    uses: ./.github/workflows/_publish_test_results.yml
    if: always()
    needs: [sbt-integration-tests]
