name: Deploy to GitHub Pages

on:
  push:
    branches: [main, dev]

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        ## TODO why do we need sbt here, if sbt unidoc is commented, where this yml file is being used?
      - name: Setup SBT
        run: |
          mkdir -p $HOME/bin/sbt
          set -eux && curl --fail --silent --location --retry 3 https://github.com/sbt/sbt/releases/download/v1.9.9/sbt-1.9.9.tgz | gunzip | tar x -C $HOME/bin/sbt
          echo "$HOME/bin/sbt" >> $GITHUB_PATH

      # - name: Generate Scaladoc
      #   run: sbt unidoc
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: documentation/package-lock.json

      - name: Install dependencies
        run: cd documentation && npm ci
      - name: Build website
        run: cd documentation &&  npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./documentation/build
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
