name: Pull Request

on:
  pull_request:
    branches: [main, dev, release-*]

jobs:
  validate-helm:
    uses: ./.github/workflows/_validate_helm.yml

  sbt-build:
    uses: ./.github/workflows/_sbt_build.yml
    with:
      preserve-cache-between-runs: true

  sbt-integration-tests:
    uses: ./.github/workflows/_scala_integration_tests.yml
    needs: [sbt-build]
    with:
      preserve-cache-between-runs: true

  publish-test-results:
    uses: ./.github/workflows/_publish_test_results.yml
    if: always()
    needs: [sbt-build, sbt-integration-tests]
