name: Bifrost_PR

on:
  pull_request:
    branches: [dev, main, release-*, rc-*, tetra]

jobs:
  sbt-build:
    uses: ./.github/workflows/_sbt_build.yml
    with:
      target-os: >-
        ["ubuntu-latest"]
      java-versions: >-
        ["11"]
      preserve-cache-between-runs: true

  post-man-integration-tests:
    uses: ./.github/workflows/_postman_integration_tests.yml
    needs: sbt-build
    with:
      target-os: >-
        ["ubuntu-latest"]
      java-versions: >-
        ["11"]
      preserve-cache-between-runs: true

  publish-test-results:
    uses: ./.github/workflows/_publish_test_results.yml
    if: always()
    needs: [post-man-integration-tests]
