name: Prerelease
on:
  release:
    types: [prereleased]
jobs:
  sbt-build:
    uses: ./.github/workflows/_sbt_build.yml
    with:
      preserve-cache-between-runs: true
  publish-docker-images-official:
    uses: ./.github/workflows/_docker_publish_official.yml
    needs: [sbt-build]
  build-artifact:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true

      - name: setup-scala
        uses: olafurpg/setup-scala@v10

      - name: assemble fat JAR
        run: sbt node/assembly

      - name: find JAR
        run: echo "JAR=$(find ./node/target/scala-2.13 -maxdepth 1 -name "*.jar")" >> $GITHUB_ENV

      - name: generate MD5 checksum
        working-directory: ./node/target/scala-2.13
        run: md5sum $(basename ${{ env.JAR }}) > "$(basename ${{ env.JAR }}).md5"

      - name: upload JAR artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ env.JAR }}
          asset_name: ${{ env.JAR }}
          asset_content_type: application/java-archive

      - name: upload MD5 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $(basename ${{ env.JAR }}).md5
          asset_name: $(basename ${{ env.JAR }}).md5
          asset_content_type: text/plain
