name: Push

on:
  pull_request:
    branches:
      - "main"

permissions:
  checks: write
  pull-requests: write
  contents: read
  packages: write
  id-token: write

jobs:
  sbt-build:
    uses: ./.github/workflows/_sbt_build.yml
    with:
      preserve-cache-between-runs: false
  sbt-integration-tests:
    uses: ./.github/workflows/_sbt_integration_tests.yml
    needs: [sbt-build]
    with:
      preserve-cache-between-runs: true
  sbt-byzantine-tests:
    uses: ./.github/workflows/_sbt_byzantine_tests.yml
    needs: [sbt-build]
    with:
      preserve-cache-between-runs: true
  publish-test-results:
    uses: ./.github/workflows/_publish_test_results.yml
    needs: [sbt-build, sbt-integration-tests, sbt-byzantine-tests]
    if: always()
  build-jar:
    uses: ./.github/workflows/_sbt_jar.yml
    needs: [sbt-build]
  publish-docker-images-unofficial:
    uses: ./.github/workflows/_docker_publish_dev.yml
    needs: [sbt-build, build-jar]
    secrets: inherit
