name: Release

on:
  push:
    branches:
      - "main"
      - "release/**"
    tags:
      - "v**"

jobs:
  validate-helm:
    uses: ./.github/workflows/_validate_helm.yml
  sbt-build:
    uses: ./.github/workflows/_sbt_build.yml
    with:
      preserve-cache-between-runs: true
  sbt-integration-tests:
    uses: ./.github/workflows/_sbt_integration_tests.yml
    needs: [sbt-build]
    with:
      preserve-cache-between-runs: true
  publish-docker-images-official:
    uses: ./.github/workflows/_docker_publish_public.yml
    needs: [sbt-build, sbt-integration-tests]
  build-jar:
    uses: ./.github/workflows/_sbt_jar.yml
    needs: [sbt-build, sbt-integration-tests]
  create-release:
    runs-on: ubuntu-latest
    needs: [sbt-build, sbt-integration-tests, build-jar]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: Bifrost Node Jar (11)

      - name: find JAR
        run: echo "JAR_LOCATION=$(find . -maxdepth 1 -name "*.jar")" >> $GITHUB_ENV

      - name: generate MD5 checksum
        run: |
          echo "MD5_LOCATION=$(basename ${{ env.JAR_LOCATION }}).md5" >> $GITHUB_ENV
          md5sum ${{ env.JAR_LOCATION }} > ${{ MD5_LOCATION }}

      - name: create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          fail_on_unmatched_files: true
          files: |
            ${{ env.JAR_LOCATION }}
            ${{ env.MD5_LOCATION }}

      - name: upload MD5 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: $(basename ${{ env.JAR }}).md5
          asset_name: $(basename ${{ env.JAR }}).md5
          asset_content_type: text/plain
