name: Upload Artifacts
on:
  push:
    branches: ["*"]
    tags: ["*"]
jobs:
  build_artifact:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout current branch (full)
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: setup-scala
        uses: olafurpg/setup-scala@v10

      - name: assemble fat JAR
        run: sbt node/assembly

      - name: find JAR
        run: JAR=$(find ./node/target/scala-2.13 -maxdepth 1 -name "*.jar")

      - name: Upload artifact
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.ACCESS_KEY }}
          secret_key: ${{ secrets.SECRET_KEY }}
          space_name: ${{ secrets.SPACE_NAME }}
          space_region: ${{ secrets.SPACE_REGION }}
          source: ${{ JAR }}
          out_dir: jars